version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "20:00"
    timezone: Asia/Tokyo
  open-pull-requests-limit: 10
  reviewers:
  - kotarella1110
  versioning-strategy: increase
  ignore:
  - dependency-name: eslint-config-airbnb-typescript
    versions:
    - 12.0.1
    - 12.2.0
    - 12.3.0
  - dependency-name: "@commitlint/cli"
    versions:
    - 12.1.0
  commit-message:
    prefix: fix
    prefix-development: chore
    include: scope
